/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DataController;
import Controller.updateController;
import Model.tableLoad;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Pathum Lahiru
 */
public class BankerPage extends javax.swing.JFrame {

    /**
     * Creates new form BankerPage
     */
    public BankerPage() {
        initComponents();
        tableLoad();
    }
 private void tableLoad() {
        tableLoad tableLoader = new tableLoad();
        ResultSet resultSet = tableLoader.fetchTableData1();
        table(resultSet);
        tableLoader.closeResources(); // Ensure resources are closed
    }

    public void table(ResultSet result) {
        BankerTable.setModel(DbUtils.resultSetToTableModel(result));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InsertBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NameBox = new javax.swing.JTextField();
        NicBox = new javax.swing.JTextField();
        ContactBox = new javax.swing.JTextField();
        PosBox = new javax.swing.JTextField();
        PassBox = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        BankerTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        DeleteBTN = new javax.swing.JButton();
        UpdateBTN = new javax.swing.JButton();
        bBackBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InsertBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        InsertBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pathum Lahiru\\Documents\\NetBeansProjects\\BankManagement\\src\\Image\\WhatsApp Image 2024-06-16 at 21.01.36 (2).jpeg")); // NOI18N
        InsertBtn.setText("Insert");
        InsertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBtnActionPerformed(evt);
            }
        });
        jPanel1.add(InsertBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("NIC");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Contact");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Position");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 60, 20));

        NameBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(NameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 90, -1));

        NicBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(NicBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 90, -1));

        ContactBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(ContactBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 90, -1));

        PosBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(PosBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 90, -1));

        PassBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(PassBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 90, -1));

        BankerTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BankerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "NIC", "Contact", "Position", "Password"
            }
        ));
        jScrollPane1.setViewportView(BankerTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 340, 90));

        jLabel6.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel6.setText("Banker Data Only");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        DeleteBTN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DeleteBTN.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pathum Lahiru\\Documents\\NetBeansProjects\\BankManagement\\src\\Image\\WhatsApp Image 2024-06-16 at 21.01.36 (1).jpeg")); // NOI18N
        DeleteBTN.setText("Delete");
        DeleteBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(DeleteBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, 40));

        UpdateBTN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UpdateBTN.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pathum Lahiru\\Documents\\NetBeansProjects\\BankManagement\\src\\Image\\WhatsApp Image 2024-06-16 at 21.01.36 (4).jpeg")); // NOI18N
        UpdateBTN.setText("Update");
        UpdateBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        UpdateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBTNActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        bBackBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bBackBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pathum Lahiru\\Documents\\NetBeansProjects\\BankManagement\\src\\Image\\icons8-back-25.png")); // NOI18N
        bBackBtn.setText("Back");
        bBackBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        bBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(bBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 70, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pathum Lahiru\\Documents\\NetBeansProjects\\BankManagement\\src\\Image\\wallpaper4.jpg")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InsertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertBtnActionPerformed
      
        String Name = NameBox.getText();
    String NIC = NicBox.getText();
    String Contact = ContactBox.getText();
    String Position = PosBox.getText();
    String Password = PassBox.getText();
    
    try {
        DataController controller = new DataController();
        controller.getData(Name, NIC, Contact, Position, Password);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
        tableLoad();
       
    }//GEN-LAST:event_InsertBtnActionPerformed

    private void UpdateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBTNActionPerformed
     String name = NameBox.getText();
    String nic = NicBox.getText();
    String contact = ContactBox.getText();
    String position = PosBox.getText();
    String password = PassBox.getText();


    try {
       
        updateController controller = new updateController();
        controller.updatpage(name,nic,contact,position,password);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter valid numerical values.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}




tableLoad();
    }//GEN-LAST:event_UpdateBTNActionPerformed

    private void bBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackBtnActionPerformed
       LoginPage LP = new LoginPage();
       LP.setVisible(true);
       this.dispose();       
    }//GEN-LAST:event_bBackBtnActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       

       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BankerTable;
    private javax.swing.JTextField ContactBox;
    private javax.swing.JButton DeleteBTN;
    private javax.swing.JButton InsertBtn;
    private javax.swing.JTextField NameBox;
    private javax.swing.JTextField NicBox;
    private javax.swing.JPasswordField PassBox;
    private javax.swing.JTextField PosBox;
    private javax.swing.JButton UpdateBTN;
    private javax.swing.JButton bBackBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
