/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Controller.AccountController;
import Controller.deleteController;
import Controller.updateController;
import Model.tableLoad;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Pathum Lahiru
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
        tableLoad();
    }
    

    
    
    private void tableLoad() {
        tableLoad tableLoader = new tableLoad();
        ResultSet resultSet = tableLoader.fetchTableData();
        table(resultSet);
        tableLoader.closeResources(); // Ensure resources are closed
    }

    public void table(ResultSet result) {
        CustomerTable.setModel(DbUtils.resultSetToTableModel(result));
    }
    

    
public void search() {
        String srch = SearchBox.getText();
        tableLoad tableLoader = new tableLoad();
        ResultSet resultSet = tableLoader.searchData(srch);
        tableSearch(resultSet);
        tableLoader.closeResources(); // Ensure resources are closed
    }

    public void tableSearch(ResultSet result) {
        CustomerTable.setModel(DbUtils.resultSetToTableModel(result));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CPasswordBox = new javax.swing.JLabel();
        CNameBox = new javax.swing.JLabel();
        CAccountTypeBox = new javax.swing.JLabel();
        CAccountNumberBox = new javax.swing.JLabel();
        NameBox = new javax.swing.JTextField();
        AccountNumber = new javax.swing.JTextField();
        PasswordBox = new javax.swing.JPasswordField();
        AccountType = new javax.swing.JComboBox<>();
        InsertBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CustomerTable = new javax.swing.JTable();
        SearchBox = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        BackBtn = new javax.swing.JButton();
        CDeleteBTN = new javax.swing.JButton();
        CUpdateBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        CPasswordBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CPasswordBox.setText("Password");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CNameBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CNameBox.setText("Name");
        getContentPane().add(CNameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, -1));

        CAccountTypeBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CAccountTypeBox.setText("Accoount Type");
        getContentPane().add(CAccountTypeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        CAccountNumberBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CAccountNumberBox.setText("Account Number");
        getContentPane().add(CAccountNumberBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        NameBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(NameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 160, 30));

        AccountNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(AccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 160, 30));

        PasswordBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(PasswordBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 160, 30));

        AccountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Saving", "Current", " " }));
        AccountType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(AccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 160, 30));

        InsertBtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        InsertBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/WhatsApp Image 2024-06-16 at 21.01.36 (2).jpeg"))); // NOI18N
        InsertBtn.setText("Insert");
        InsertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBtnActionPerformed(evt);
            }
        });
        getContentPane().add(InsertBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 219, -1, 40));

        CustomerTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        CustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Account Type", "Account Number", "Password"
            }
        ));
        jScrollPane1.setViewportView(CustomerTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 360, 90));

        SearchBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Box"));
        SearchBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchBoxKeyReleased(evt);
            }
        });
        getContentPane().add(SearchBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 170, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pathum Lahiru\\Downloads\\icons8-back-25.png")); // NOI18N
        BackBtn.setText("Back");
        BackBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 120, 30));

        CDeleteBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/WhatsApp Image 2024-06-16 at 21.01.36 (1).jpeg"))); // NOI18N
        CDeleteBTN.setText("Delete");
        CDeleteBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        CDeleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDeleteBTNActionPerformed(evt);
            }
        });
        jPanel1.add(CDeleteBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 120, -1));

        CUpdateBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/WhatsApp Image 2024-06-16 at 21.01.36 (4).jpeg"))); // NOI18N
        CUpdateBTN.setText("Update");
        CUpdateBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        CUpdateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CUpdateBTNActionPerformed(evt);
            }
        });
        jPanel1.add(CUpdateBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 110, -1));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Customer Data Only");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 240, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 184, 80, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/wallpaper4.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InsertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertBtnActionPerformed
    String Name = NameBox.getText();
    String Account_Type = (String) AccountType.getSelectedItem();
    String Account_Number =AccountNumber.getText();
    String Password = PasswordBox.getText();
    
    try {
        AccountController controller = new AccountController();
        controller.getData(Name, Account_Type, Account_Number, Password);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
        tableLoad();
    }//GEN-LAST:event_InsertBtnActionPerformed

    private void SearchBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchBoxKeyReleased
search();        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBoxKeyReleased

    private void CDeleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDeleteBTNActionPerformed
        String idText = NameBox.getText();
        
        
      
       try {
          
            deleteController controller = new deleteController();
            controller.deletCustomer(idText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numerical values.", "Error", JOptionPane.ERROR_MESSAGE);
}


tableLoad();
    }//GEN-LAST:event_CDeleteBTNActionPerformed

    private void CUpdateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUpdateBTNActionPerformed
        String Name = NameBox.getText();
    String Account_Type = (String) AccountType.getSelectedItem();
    String Account_Number =AccountNumber.getText();
    String Password = PasswordBox.getText();
    


    try {
       

        updateController controller = new updateController();
        controller.updatecustomer(Name,Account_Type,Account_Number,Password);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter valid numerical values.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}




 tableLoad();
        
        
    }//GEN-LAST:event_CUpdateBTNActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
         LoginPage LP = new LoginPage();
       LP.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccountNumber;
    private javax.swing.JComboBox<String> AccountType;
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel CAccountNumberBox;
    private javax.swing.JLabel CAccountTypeBox;
    private javax.swing.JButton CDeleteBTN;
    private javax.swing.JLabel CNameBox;
    private javax.swing.JLabel CPasswordBox;
    private javax.swing.JButton CUpdateBTN;
    private javax.swing.JTable CustomerTable;
    private javax.swing.JButton InsertBtn;
    private javax.swing.JTextField NameBox;
    private javax.swing.JPasswordField PasswordBox;
    private javax.swing.JTextField SearchBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
