/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.loginController;
import javax.swing.JOptionPane;

/**
 *
 * @author Pathum Lahiru
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bankId = new javax.swing.JTextField();
        BankerpWbox = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CustomerId = new javax.swing.JTextField();
        CustomerPwbox = new javax.swing.JPasswordField();
        BankerlgBtn = new javax.swing.JButton();
        CustomerLgBtn = new javax.swing.JButton();
        HomeLgbtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Banker");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Customer");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Banker Id");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        bankId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankIdActionPerformed(evt);
            }
        });
        jPanel1.add(bankId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 80, -1));

        BankerpWbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankerpWboxActionPerformed(evt);
            }
        });
        jPanel1.add(BankerpWbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Customer Id");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));
        jPanel1.add(CustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 100, -1));
        jPanel1.add(CustomerPwbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 100, -1));

        BankerlgBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        BankerlgBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pathum Lahiru\\Documents\\NetBeansProjects\\BankManagement\\src\\Image\\icons8-login-25.png")); // NOI18N
        BankerlgBtn.setText("Login");
        BankerlgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankerlgBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BankerlgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, 30));

        CustomerLgBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        CustomerLgBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pathum Lahiru\\Documents\\NetBeansProjects\\BankManagement\\src\\Image\\icons8-login-25.png")); // NOI18N
        CustomerLgBtn.setText("Login");
        CustomerLgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerLgBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CustomerLgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, 30));

        HomeLgbtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        HomeLgbtn.setText("Home");
        HomeLgbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeLgbtnActionPerformed(evt);
            }
        });
        jPanel1.add(HomeLgbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/union bank .png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        BackBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        exit.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pathum Lahiru\\Documents\\NetBeansProjects\\BankManagement\\src\\Image\\loggg.jpg")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BankerpWboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankerpWboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BankerpWboxActionPerformed

    private void BankerlgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankerlgBtnActionPerformed
        String BankerID = bankId.getText();
    String pass = new String(BankerpWbox.getPassword());

    loginController controller = new loginController();
    boolean isValid = controller.validateLogin(BankerID, pass);

    if (isValid) {
        BankerPage obj = new BankerPage();
        obj.setVisible(true);
        this.dispose();       
    } else {
     
        JOptionPane.showMessageDialog(this, "Invalid BankerId or Password");
}

                       

        
    }//GEN-LAST:event_BankerlgBtnActionPerformed

    private void CustomerLgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerLgBtnActionPerformed
  /*
       String userId = CustomerId.getText();
    String pass = new String(CustomerPwbox.getPassword());

    loginController controller = new loginController();
    boolean isValid = controller.validateLogin(userId, pass);

    if (isValid) {
        Customer obj = new Customer();
        obj.setVisible(true);
        this.dispose();       
    } else {
     
        JOptionPane.showMessageDialog(this, "Invalid BankerId or Password");
}
    */  
  Customer obj = new Customer();
        obj.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_CustomerLgBtnActionPerformed

    
    private void HomeLgbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeLgbtnActionPerformed
         Home HP = new Home();
       HP.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_HomeLgbtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
         Home HP = new Home();
       HP.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void bankIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankIdActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton BankerlgBtn;
    private javax.swing.JPasswordField BankerpWbox;
    private javax.swing.JTextField CustomerId;
    private javax.swing.JButton CustomerLgBtn;
    private javax.swing.JPasswordField CustomerPwbox;
    private javax.swing.JButton HomeLgbtn;
    private javax.swing.JTextField bankId;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
